# .github/workflows/futureskills-ci-cd.yml
name: FutureSkillsSyntax CI/CD Pipeline

on:
  push:
    branches: [ main, develop, release/* ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Daily security scans at 2 AM
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      deploy_type:
        description: 'Deployment type'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - backend
        - frontend
        - database

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_REGION: us-east-1
  ECR_REPOSITORY: futureskillssyntax

jobs:
  # Security Scanning
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy results
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Run Bandit security linter
      run: |
        cd backend
        pip install bandit
        bandit -r app -f json -o bandit-report.json
    
    - name: Check for secrets in code
      uses: secret-scanner/action@v2.0.0
      with:
        paths: ./
    
    - name: Dependency audit
      run: |
        cd backend
        pip install safety
        safety check --full-report

  # Backend Tests
  backend-test:
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name != 'workflow_dispatch'
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          timeout: 5s
          retries: 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd backend
        pip install -e ".[dev]"
    
    - name: Run tests with coverage
      run: |
        cd backend
        pytest tests/ \
          --cov=app \
          --cov-report=xml \
          --cov-report=html \
          --cov-fail-under=80 \
          -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: unittests
        name: codecov-umbrella
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: ./backend/htmlcov/

  # Frontend Tests
  frontend-test:
    runs-on: ubuntu-latest
    needs: security-scan
    if: github.event_name != 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/web/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend/web
        npm ci
    
    - name: Run tests
      run: |
        cd frontend/web
        npm test -- --coverage
    
    - name: Run Cypress E2E tests
      uses: cypress-io/github-action@v5
      with:
        working-directory: frontend/web
        start: npm run dev
        wait-on: 'http://localhost:5173'
    
    - name: Upload frontend coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/web/coverage/lcov.info
        flags: frontend

  # Linting and Code Quality
  code-quality:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    if: github.event_name != 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run Black code formatter
      run: |
        cd backend
        black --check --diff app tests
    
    - name: Run isort import sorter
      run: |
        cd backend
        isort --check-only --diff app tests
    
    - name: Run flake8 linter
      run: |
        cd backend
        flake8 app tests --max-line-length=88
    
    - name: Run mypy type checker
      run: |
        cd backend
        mypy app
    
    - name: Run ESLint
      run: |
        cd frontend/web
        npm run lint
    
    - name: Run TypeScript type check
      run: |
        cd frontend/web
        npx tsc --noEmit
    
    - name: Run Prettier check
      run: |
        cd frontend/web
        npx prettier --check .

  # Build and Push Backend
  build-backend:
    runs-on: ubuntu-latest
    needs: code-quality
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: 'true'
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}-backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
    
    - name: Scan image with Trivy
      run: |
        trivy image --exit-code 1 \
          --severity CRITICAL,HIGH \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}

  # Build and Push Frontend
  build-frontend:
    runs-on: ubuntu-latest
    needs: code-quality
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/web/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend/web
        npm ci
    
    - name: Build frontend
      run: |
        cd frontend/web
        npm run build
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend/web
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Deploy to Staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to ECS
      run: |
        # Update backend service
        aws ecs update-service \
          --cluster futureskills-staging \
          --service futureskills-backend \
          --force-new-deployment \
          --no-cli-pager
        
        echo "Backend deployment initiated"
        
        # Wait for backend to stabilize
        sleep 30
        
        # Update frontend service
        aws ecs update-service \
          --cluster futureskills-staging \
          --service futureskills-frontend \
          --force-new-deployment \
          --no-cli-pager
        
        echo "Frontend deployment initiated"
    
    - name: Run database migrations
      run: |
        aws ecs run-task \
          --cluster futureskills-staging \
          --task-definition futureskills-migrations \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.SUBNET_ID_1 }},${{ secrets.SUBNET_ID_2 }}],securityGroups=[${{ secrets.SECURITY_GROUP_ID }}],assignPublicIp=DISABLED}" \
          --no-cli-pager
    
    - name: Run smoke tests
      run: |
        # Wait for services to be healthy
        sleep 60
        
        # Test backend health
        BACKEND_HEALTH=$(curl -s -o /dev/null -w "%{http_code}" https://api.staging.futureskillssyntax.com/health)
        if [ "$BACKEND_HEALTH" != "200" ]; then
          echo "Backend health check failed: $BACKEND_HEALTH"
          exit 1
        fi
        
        # Test frontend
        FRONTEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://app.staging.futureskillssyntax.com)
        if [ "$FRONTEND_STATUS" != "200" ]; then
          echo "Frontend check failed: $FRONTEND_STATUS"
          exit 1
        fi
        
        echo "Smoke tests passed!"
    
    - name: Notify Slack
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "✅ Staging Deployment Successful"
        SLACK_MESSAGE: "FutureSkillsSyntax v${{ needs.build-backend.outputs.image_tag }} deployed to staging"
        SLACK_COLOR: "good"

  # Deploy to Production
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/release/production' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Create production tag
      run: |
        git tag -a "v$(date +%Y.%m.%d)-$(git rev-parse --short HEAD)" -m "Production release"
        git push origin --tags
    
    - name: Deploy backend to production
      run: |
        # Update backend service with blue/green deployment
        aws ecs update-service \
          --cluster futureskills-production \
          --service futureskills-backend \
          --force-new-deployment \
          --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100" \
          --no-cli-pager
        
        echo "Production backend deployment initiated (blue/green)"
        
        # Wait for deployment to complete
        echo "Waiting for deployment to stabilize..."
        sleep 120
        
        # Verify deployment
        DEPLOYMENT_STATUS=$(aws ecs describe-services \
          --cluster futureskills-production \
          --service futureskills-backend \
          --query 'services[0].deployments[?status==`PRIMARY`].runningCount' \
          --output text)
        
        if [ "$DEPLOYMENT_STATUS" -eq 0 ]; then
          echo "Deployment failed!"
          exit 1
        fi
        
        echo "Backend deployment successful"
    
    - name: Run database migrations
      run: |
        # Run migrations with rollback capability
        aws ecs run-task \
          --cluster futureskills-production \
          --task-definition futureskills-migrations \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.PROD_SUBNET_ID_1 }},${{ secrets.PROD_SUBNET_ID_2 }}],securityGroups=[${{ secrets.PROD_SECURITY_GROUP_ID }}],assignPublicIp=DISABLED}" \
          --overrides '{"containerOverrides": [{"name": "migrations", "command": ["python", "-m", "alembic", "upgrade", "head"]}]}' \
          --no-cli-pager
        
        echo "Database migrations initiated"
    
    - name: Deploy frontend to production
      run: |
        # Deploy frontend with CloudFront invalidation
        cd frontend/web
        npm run build
        
        # Upload to S3
        aws s3 sync dist/ s3://${{ secrets.PRODUCTION_S3_BUCKET }} \
          --delete \
          --cache-control "public, max-age=31536000"
        
        # Create CloudFront invalidation
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.PRODUCTION_CLOUDFRONT_ID }} \
          --paths "/*"
        
        echo "Frontend deployed to S3 and CloudFront"
    
    - name: Run comprehensive tests
      run: |
        # API tests
        echo "Running API tests..."
        curl -f https://api.futureskillssyntax.com/health || exit 1
        
        # Load test (sample)
        echo "Running load test..."
        for i in {1..10}; do
          curl -s https://api.futureskillssyntax.com/health > /dev/null
        done
        
        # Check application endpoints
        echo "Checking application endpoints..."
        ENDPOINTS=(
          "https://api.futureskillssyntax.com/api/v1/auth/health"
          "https://app.futureskillssyntax.com"
          "https://admin.futureskillssyntax.com"
        )
        
        for endpoint in "${ENDPOINTS[@]}"; do
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint")
          if [ "$STATUS" -ge 400 ]; then
            echo "Endpoint $endpoint failed with status $STATUS"
            exit 1
          fi
          echo "✓ $endpoint"
        done
        
        echo "All tests passed!"
    
    - name: Update deployment status
      run: |
        # Update deployment tracking
        DEPLOYMENT_ID=$(aws deploy create-deployment \
          --application-name FutureSkillsSyntax \
          --deployment-group-name production \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
          --description "Production deployment ${{ github.sha }}" \
          --query 'deploymentId' \
          --output text)
        
        echo "Deployment ID: $DEPLOYMENT_ID"
    
    - name: Notify on success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "🚀 Production Deployment Successful"
        SLACK_MESSAGE: "FutureSkillsSyntax v${{ needs.build-backend.outputs.image_tag }} deployed to production"
        SLACK_COLOR: "good"
    
    - name: Rollback on failure
      if: failure()
      run: |
        echo "Deployment failed, initiating rollback..."
        
        # Rollback ECS service
        aws ecs update-service \
          --cluster futureskills-production \
          --service futureskills-backend \
          --force-new-deployment \
          --no-cli-pager
        
        # Notify failure
        curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ Production deployment failed for ${{ github.sha }}\"}" \
          ${{ secrets.SLACK_WEBHOOK }}
        
        exit 1

  # Cleanup old images
  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs: [deploy-staging, deploy-production]
    
    steps:
    - name: Clean up old ECR images
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Remove old images
      run: |
        # Keep only last 10 images
        aws ecr describe-images \
          --repository-name ${{ env.ECR_REPOSITORY }}-backend \
          --query 'imageDetails[*].imageTags[0]' \
          --output text | sort -r | tail -n +11 | xargs -I {} aws ecr batch-delete-image \
          --repository-name ${{ env.ECR_REPOSITORY }}-backend \
          --image-ids imageTag={}